# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  dist: "dist"  
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"

    # Next two lines add location of FontAwesome font assets.
    - "node_modules/font-awesome/**/*"
    - "!node_modules/font-awesome/{css,less,scss}/**/*" #

  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"

    # Next line adds FontAwesome SCSS assets
    - "node_modules/font-awesome/scss"

  entries:
    - "src/assets/js/app.js"